### ISSUE TITLE
the predict.py is not exist here, can you share the script?

### ISSUE THREAD

**Issue by SongPool** [Haoyu-Xie/PRCL#3]

**Comment by Haoyu-Xie** [comment]
Sorry, I don't know what file you are referring to.
Could you explain in more details please?

**Comment by SongPool** [comment]
just the script that use trained model to segment images and show the result, Thanks

**Comment by WangChangqi98** [comment]
We have uploaded the script visual.py.

**Comment by SongPool** [comment]
Thanks for your work

**Comment by WangChangqi98** [comment]
You are welcome.
